### ISSUE TITLE
Failed to unmarshal json payload!

### ISSUE THREAD

**Issue by rednas0812** [ThrillQuks/Pitraix#21]
**What operating system are you using? (exact version)**
- Fill here

**What operating system is the host running? (exact version)**
- Fill here

**Are you using Release or master?**
- Fill here

** Did you or the host have TOR previously installed?**
- Fill here

**Are you running both OPER and lyst payload on same machine?**
- Fill here

**Did you compile OPER and lyst payloads according to the README.md?**
- Fill here

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ThrillQuks** [comment]
how am i supposed to fix if you don't give information? closing this

**Comment by ThrillQuks** [comment]
on odd note this is related to latest update
from release notes:
`Hostring file should now include the active Anti-Malware on the host, as well as Mac Address (you should backup your old hostring.json cuz it might not be compaitable)`
