### ISSUE TITLE
Time to be smoll

### ISSUE THREAD

**Issue by ThrillQuks** [ThrillQuks/Pitraix#5]
time to take the 3 huge source files and split each of them into tiny pieces because apparently it's "messy" when i don't have a file for each function but fine. 

this issue is open until i or somebody feels like to actually go on doing that meaningless eye candy thing

**Comment by Wissotsky** [comment]
I'd be up to do some refactoring.

I think the most important thing with this is to add unit testing so new contributors can easily get onboard the project.

Also modularising the executor(Lyst) into a base one which establishes connections + can self update, with more specific features like ransom,mining,proxy,script etc etc living in optional modules will allow other developers to customize it to their needs and share their work significantly easier.

**Comment by ThrillQuks** [comment]
> Also modularising the executor(Lyst) into a base one which establishes connections + can self update, with more specific features like ransom,mining,proxy,script etc etc living in optional modules will allow other developers to customize it to their needs and share their work significantly easier.

This actually sounds very good, well at least until you read the source code. let's take Ransom/Decrypt instructions as example ok? those instructions use the already imported AES library so If I were to turn entire code into a OOP it wouldn't really matter or affect size at all. But yeah this will probably be the path I go down in

**Comment by reneManqueros** [comment]
I'd be willing to do the refactoring, create entities, convert some stuff to structs + function receivers, add viper/cobra, dockerize it, etc

**Comment by ThrillQuks** [comment]
> I'd be willing to do the refactoring, create entities, convert some stuff to structs + function receivers, add viper/cobra, dockerize it, etc

go ahead (no pun intended) and fork it and work on that, i will replace the bulky files once you are finished

**Comment by ThrillQuks** [comment]
I added modules support, code will not get much bigger after the two release, closing this because my coding is bootiful
